{{- if .Values.enabled }}
{{- if and .Values.rules.specifiedInValues .Values.rules.value }}
apiVersion: {{ template "prometheus-operator.apiVersion" . }}
kind: PrometheusRule
metadata:
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ template "prometheus.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{- if .Values.rules.additionalLabels }}
{{ toYaml .Values.rules.additionalLabels | indent 4 }}
    {{- end }}
  name: {{ template "prometheus.fullname" . }}-extras
spec:
  groups:
{{ if .Values.rules.value }}
{{- toYaml .Values.rules.value | indent 2 }}
{{ end }}
{{- end }}
{{- end }}