{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus.dnsname" . }}
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ template "prometheus.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  sessionAffinity: "{{ .Values.service.sessionAffinity }}"
{{- if .Values.service.clusterIP }}
  clusterIP: "{{ .Values.service.clusterIP }}"
{{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
{{- end }}
{{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
  ports:
    - name: http
    {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
    {{- end }}
      port: 9090
      targetPort: web
      protocol: TCP
  selector:
    app: {{ template "prometheus.name" . }}
    prometheus: {{ .Release.Name }}
  type: "{{ .Values.service.type }}"
{{- end }}
