apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "prometheus-operator.fullname" . }}
data:
  servicemonitor-operator.yaml: |-
      apiVersion: {{ template "prometheus-operator.apiVersion" . }}
      kind: ServiceMonitor
      metadata:
        labels:
          app: {{ template "prometheus-operator.name" . }}
          chart: {{ template "prometheus-operator.version" . }}
          heritage: {{ .Release.Service }}
          release: {{ .Release.Name }}
        name: {{ template "prometheus-operator.fullname" . }}
      spec:
        jobLabel: {{ .Values.operator.jobLabel }}
        selector:
          matchLabels:
            operated-prometheus: "true"
        namespaceSelector:
          matchNames:
            - {{ .Release.Namespace | quote }}
        endpoints:
        - port: http
          interval: 30s
          honorLabels: true
