apiVersion: {{ template "prometheus-operator.apiVersion" . }}
kind: ServiceMonitor
metadata:
  labels:
    app: {{ template "exporter-kubelets.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: kubelets
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    prometheus: {{ .Release.Name }}
    {{- if .Values.additionalServiceMonitorLabels }}
{{ toYaml .Values.additionalServiceMonitorLabels | indent 4 }}
    {{- end }}    
  name: {{ template "exporter-kubelets.fullname" . }}
spec:
  jobLabel: component
  selector:
    matchLabels:
      k8s-app: kubelet
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  {{- if .Values.https }}
  - port: https-metrics
    scheme: https
    interval: 15s
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      {{- if .Values.insecureSkipVerify }}
      insecureSkipVerify: true
      {{- end }}
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    # relabelings:
    #   - action: labelmap
    #     regex: __meta_kubernetes_node_label_(.+)
    #   - targetLabel: __address__
    #     replacement: kubernetes.default.svc:443
    #   - sourceLabels: [__meta_kubernetes_node_name]
    #     regex: (.+)
    #     targetLabel: __metrics_path__
    #     replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
  - port: https-metrics
    scheme: https
    path: /metrics/cadvisor
    interval: 30s
    honorLabels: true
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      {{- if .Values.insecureSkipVerify }}
      insecureSkipVerify: true
      {{- end }}
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    # relabelings:
    #   - action: labelmap
    #     regex: __meta_kubernetes_node_label_(.+)
    #   - targetLabel: __address__
    #     replacement: kubernetes.default.svc:443
    #   - sourceLabels: [__meta_kubernetes_node_name]
    #     regex: (.+)
    #     targetLabel: __metrics_path__
    #     replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
  {{- else }}
  - port: http-metrics
    interval: 15s
  - port: cadvisor
    interval: 30s
    honorLabels: true
  {{- end }}
