{{- if .Values.enabled }}
{{- if not .Values.configFromSecret }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "alertmanager.name" . }}
    chart: {{ template "alertmanager.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "alertmanager.fullname" . }}
data:
  alertmanager.yaml: {{ toYaml .Values.config | b64enc | quote }}
{{- range $key, $val := .Values.templateFiles }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
