{{- if .Values.enabled }}
{{- if and .Values.global.rbacEnable .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ template "prometheus.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "prometheus.serviceAccountName" .}}
imagePullSecrets: 
{{ toYaml .Values.global.imagePullSecrets | indent 2 }}
{{- end }}
{{- end }}