apiVersion: v1
description: A Helm chart for Kubernetes
name: exporter-kubelets
appVersion: "v2.3.2"
version: 0.2.11
maintainers:
  - name: Michael Goodness
    email: mgoodness@gmail.com
  - name: Giancarlo Rubio
    email: gianrubio@gmail.com
