apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "exporter-kube-state.fullname" . }}
  labels:
    app: {{ template "exporter-kube-state.name" . }}
    component: kube-state
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  NannyConfiguration: |-
    apiVersion: nannyconfig/v1alpha1
    kind: NannyConfiguration
    baseCPU: {{ .Values.addon_resizer.cpu }}
    cpuPerNode: {{ .Values.addon_resizer.extra_cpu }}
    baseMemory: {{ .Values.addon_resizer.memory }}
    memoryPerNode: {{ .Values.addon_resizer.extra_memory }}
