{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "grafana.name" . }}
    chart: {{ template "grafana.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
  name: {{ template "grafana.dnsname" . }}
  {{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
spec:
  ports:
    - name: grafana
      port: 3000
      targetPort: grafana
{{- if contains "NodePort" .Values.service.type }}
  {{- if .Values.service.nodePort }}
      nodePort:  {{ .Values.service.nodePort }}
  {{- end }}
{{- end }}
  selector:
    app: {{ template "grafana.name" . }}
    release: {{ .Release.Name }}
  type: "{{ .Values.service.type }}"
{{- if contains "LoadBalancer" .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end -}}
  {{- if .Values.service.loadBalancerSourceRanges}}
  loadBalancerSourceRanges:
  {{- range .Values.service.loadBalancerSourceRanges }}
  - {{ . }}
  {{- end }}
  {{- end -}}
{{- end -}}
{{- end }}