apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: "{{ .Release.Name }}-crt"
spec:
  secretName: "{{ .Release.Name }}-crt"
  acme:
    config:
    - http01:
        ingress: {{ template "docker-registry.fullname" . }}
      domains:
      - xip.io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
