{{- if .Values.enabled }}
{{- if and (and .Values.config.specifiedInValues .Values.config.value ) ( not .Values.serviceMonitorSelector ) }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ template "prometheus.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "prometheus.fullname" . }}
data:
  configmaps.json: {{ include (print  (dir $.Template.Name) "/_configmaps.json.tpl") . | b64enc | quote }}
  prometheus.yaml: {{ toYaml .Values.config.value | b64enc | quote }}
{{- end }}

---

{{- if .Values.additionalScrapeConfigs }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ template "prometheus.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "prometheus.fullname" . }}-additional-scrape-configs
data:
  additional-scrape-configs.yaml: {{ toYaml .Values.additionalScrapeConfigs | b64enc | quote }}
{{- end }}

---

{{- if .Values.additionalAlertManagerConfigs }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ template "prometheus.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "prometheus.fullname" . }}-additional-alertmanager-configs
data:
  additional-alertmanager-configs.yaml: {{ toYaml .Values.additionalAlertManagerConfigs | b64enc | quote }}
{{- end }}
{{- end }}
