{{- if .Values.endpoints }}
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: {{ template "exporter-node.name" . }}
    chart: {{ template "exporter-node.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "exporter-node.fullname" . }}
subsets:
  - addresses:
      {{- range .Values.endpoints }}
      - ip: {{ . }}
      {{- end }}
    ports:
      - name: metrics
        port: {{ .Values.nodeExporterPort }}
        protocol: TCP
{{- end }}
