{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "prometheus.nginx.fullname" . }}
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ template "prometheus.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  auto;
    error_log  /dev/null warn;
    pid        /var/run/nginx.pid;
    events {
      worker_connections  1024;
    }
    http {
      server {
        access_log  off;
        
        listen 80;
        location / {
          proxy_set_header Accept-Encoding "";
          proxy_pass http://prometheus-operated.{{ .Release.Namespace }}:9090/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;

          # sub_filter_types text/html;
          sub_filter_once off;
          ## APPEARS TO BE UNNECESSARY? sub_filter '="/static/' '="/static/prometheus/';
        }
      }
    }

{{- end }}