apiVersion: v1
kind: Service
metadata:
  name: {{ template "exporter-kube-state.dnsname" . }}
  labels:
    app: {{ template "exporter-kube-state.name" . }}
    chart: {{ template "exporter-kube-state.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.kube_state_metrics.service.type }}
  ports:
  - port: {{ .Values.kube_state_metrics.service.externalPort }}
    targetPort: {{ .Values.kube_state_metrics.service.internalPort }}
    protocol: TCP
    name: {{ .Values.kube_state_metrics.service.name }}
  selector:
    app: {{ template "exporter-kube-state.name" . }}
    release: {{ .Release.Name }}
