{{- if .Values.global.rbacEnable }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ template "exporter-kube-state.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "exporter-kube-state.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "exporter-kube-state.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "exporter-kube-state.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
