apiVersion: v1
kind: Service
metadata:
  name: {{ template "exporter-node.dnsname" . }}
  labels:
    app: {{ template "exporter-node.name" . }}
    chart: {{ template "exporter-node.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ template "exporter-node.name" . }}
    release: {{ .Release.Name }}
  ports:
  - name: metrics
    port: 9100
    targetPort: metrics
    protocol: TCP
{{- if .Values.enableDaemonSet }}
  type: {{ .Values.service.type }}
{{- else }}
  type: ClusterIP
  clusterIP: None
{{- end }}
