{{- if .Values.enabled }}
{{- $app := include "prometheus.name" . -}}
{{- $chart := include "prometheus.version" . -}}
{{- $heritage := .Release.Service -}}
{{- $release := .Release.Name -}}
{{- if .Values.serviceMonitors }}
apiVersion: v1
kind: List
items:
{{- range .Values.serviceMonitors }}
  - apiVersion: {{ template "prometheus-operator.apiVersion" . }}
    kind: ServiceMonitor
    metadata:
      labels:
        app: {{ $app }}
        chart: {{ $chart }}
        heritage: {{ $heritage }}
        release: {{ $release }}
        {{- if .serviceMonitorSelectorLabels }}
{{ toYaml .serviceMonitorSelectorLabels | indent 8 }}
        {{- end }}
      name: {{ .name }}
    spec:
      endpoints:
{{ toYaml .endpoints | indent 8 }}
    {{- if .jobLabel }}
      jobLabel: {{ .jobLabel }}
    {{- end }}
    {{- if .namespaceSelector }}
      namespaceSelector:
{{ toYaml .namespaceSelector | indent 8 }}
    {{- end }}
      selector:
{{ toYaml .selector | indent 8 }}
{{- end }}
{{- end }}
{{- end }}
