apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "grafana.fullname" . }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "grafana.server.fullname" . }}
spec:
  replicas: 1
  template:
    metadata:
      annotations:
      {{- range $key, $value := .Values.annotations }}
        {{ $key }}: {{ $value }}
      {{- end }}
      labels:
        app: {{ template "grafana.fullname" . }}
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: grafana
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "{{ .Values.auth.anonymous.enabled }}"
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "grafana.server.fullname" . }}
              key: user
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "grafana.server.fullname" . }}
              key: password
        - name: GF_SERVER_ROOT_URL
          value: '%(protocol)s://%(domain)s/k8s/clusters/{{ .Values.rancherClusterId }}/api/v1/namespaces/{{ .Release.Namespace }}/services/http:grafana-nginx:80/proxy/'
{{- if .Values.extraVars }}
{{ toYaml .Values.extraVars | indent 8 }}
{{- end }}
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
      {{- if .Values.mountGrafanaConfig }}
        - name: grafana-config
          mountPath: /etc/grafana
      {{- end }}
        ports:
        - name: grafana
          containerPort: 3000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
        {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        {{- end }}
      - name: grafana-watcher
        image: {{ .Values.grafanaWatcher.repository }}:{{ .Values.grafanaWatcher.tag }}
        args:
          - '--watch-dir=/var/grafana-dashboards'
          - '--grafana-url=http://127.0.0.1:3000'
          {{- range .Values.serverDashboardConfigmaps }}
          - '--watch-dir=/var/additional-dashboards/{{ . }}'
          {{- end }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:
        - name: GRAFANA_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "grafana.server.fullname" . }}
              key: user
        - name: GRAFANA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "grafana.server.fullname" . }}
              key: password
        {{- if .Values.grafanaWatcher.resources }}
        resources:
{{ toYaml .Values.grafanaWatcher.resources | indent 12 }}
        {{- end }}
        volumeMounts:
          - name: grafana-dashboards
            mountPath: /var/grafana-dashboards
    {{- range .Values.serverDashboardConfigmaps }}
          - name: {{ . }}
            mountPath: /var/additional-dashboards/{{ . }}
    {{- end }}
      - name: grafana-proxy
        image: {{ .Values.grafanaProxy.repository }}:{{ .Values.grafanaProxy.tag }}
        args:
        - nginx
        - -g
        - daemon off;
        - -c
        - /nginx/nginx.conf
        volumeMounts:
        - mountPath: /nginx/
          name: grafana-nginx
    {{- if .Values.nodeSelector }}
      nodeSelector:
    {{ toYaml .Values.nodeSelector | indent 4 }}
    {{- end }}
    {{- if .Values.global.rbacEnable }}
      serviceAccountName: {{ template "grafana.server.fullname" . }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
      volumes:
      - name: grafana-storage
        {{- if .Values.storageSpec }}
        persistentVolumeClaim:
          claimName: {{ template "grafana.server.fullname" . }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: grafana-nginx
        configMap:
          defaultMode: 438
          items:
          - key: nginx.conf
            mode: 438
            path: nginx.conf
          name: {{ template "grafana.server.fullname" . }}-nginx
      - name: grafana-dashboards
        configMap:
          name: {{ template "grafana.server.fullname" . }}
      {{- if .Values.mountGrafanaConfig }}
        - name: grafana-config
          hostPath:
            path: /etc/grafana
            type: Directory
      {{- end }}
      {{- range .Values.serverDashboardConfigmaps }}
        - name: {{ . }}
          configMap:
            name: {{ . }}
      {{- end }}
