apiVersion: v1
kind: Service
metadata:
  name: grafana-nginx
  labels:
    app: {{ template "grafana.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    kubernetes.io/cluster-service: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: {{ template "grafana.fullname" . }}
