apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "grafana.server.fullname" . }}-nginx
  labels:
    app: {{ template "grafana.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
      server {
        listen 80;
        gzip on;
        gzip_min_length 1k;
        gzip_comp_level 2;
        gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png;
        gzip_vary on;
        gzip_disable "MSIE [1-6]\.";
        include /etc/nginx/mime.types;

        location / {
          proxy_pass http://localhost:3000/;
          sub_filter_types text/html;
          sub_filter '<base href="/k8s/clusters/{{ .Values.rancherClusterId }}/api/v1/namespaces/{{ .Release.Namespace }}/services/http:grafana-nginx:80/proxy/" />' '<base href="/" />';
        }
      }
    }
