{{- if .Values.operator.rbacEnable }}
{{- if .Values.operator.pspEnable }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ template "prometheus-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: psp-{{ template "prometheus-operator.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-{{ template "prometheus-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "prometheus-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
