apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "exporter-kube-state.fullname" . }}
  labels:
    app: {{ template "exporter-kube-state.name" . }}
    chart: {{ template "exporter-kube-state.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  NannyConfiguration: |-
    apiVersion: nannyconfig/v1alpha1
    kind: NannyConfiguration
    baseCPU: {{ .Values.addon_resizer.cpu }}
    cpuPerNode: {{ .Values.addon_resizer.extra_cpu }}
    baseMemory: {{ .Values.addon_resizer.memory }}
    memoryPerNode: {{ .Values.addon_resizer.extra_memory }}
