{{- if .Values.enabled }}
{{- if or .Values.storageSpec .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ template "grafana.name" . }}
    chart: {{ template "grafana.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "grafana.fullname" . }}
spec:
  {{- if .Values.storageSpec }}
{{ toYaml .Values.storageSpec | indent 2 }}
  {{- else }}
  accessModes:
    - {{ default "ReadWriteOnce" .Values.persistence.accessMode }}
  storageClassName: {{ default "default" .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- end }}
{{- end -}}
{{- end }}