## CRD apiGroup
##
apiGroup: "monitoring.coreos.com"

## Using default rules which are in templates/kubernetes.rules.yaml
##
enabledDefaultPrometheusRules: true

## Custome rules
##
prometheusRules: []

## Custom Labels to be added to ServiceMonitor
##
additionalServiceMonitorLabels: {}
##Custom Labels to be added to Prometheus Rules CRD
##
additionalRulesLabels: {}
