{{- if or .Values.enabledDefaultPrometheusRules .Values.prometheusRule }}
apiVersion: {{ template "prometheus-operator.apiVersion" . }}
kind: PrometheusRule
metadata:
  labels:
    app: {{ template "exporter-kube-state.name" . }}
    chart: {{ template "exporter-kube-state.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{- if .Values.additionalRulesLabels }}
{{ toYaml .Values.additionalRulesLabels | indent 4 }}
    {{- else if .Values.additionalRulesConfigMapLabels }}       # Deprecated for .Values.additionalRulesLabels
{{ toYaml .Values.additionalRulesConfigMapLabels | indent 4 }}  # Deprecated for .Values.additionalRulesLabels
    {{- end }} 
  name: {{ template "exporter-kube-state.fullname" . }}
spec:
  groups:
{{ if .Values.enabledDefaultPrometheusRules }}
{{- include "kube-state-metrics.rules.yaml.tpl" . | indent 2 }}
{{ end }}
{{ if .Values.prometheusRules }}
{{- toYaml .Values.prometheusRules | indent 2 }}
{{ end }}
{{- end }}
