{{- if .Values.global.rbacEnable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "exporter-kube-state.name" . }}
    chart: {{ template "exporter-kube-state.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "exporter-kube-state.fullname" . }}
imagePullSecrets: 
{{ toYaml .Values.global.imagePullSecrets | indent 2 }}
{{- end }}
