apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "prometheus.fullname" . }}-nginx
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    {{ if empty .Values.prometheusLabelValue -}}
    prometheus: {{ template "prometheus.fullname" . }}
    {{- else -}}
    prometheus: {{ .Values.prometheusLabelValue }}
    {{- end }}
    release: {{ .Release.Name }}
    component: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "prometheus.name" . }}
      component: nginx-proxy
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "prometheus.name" . }}
        component: nginx-proxy
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: nginx
        image: docker-registry.saicstack.com/rancher/nginx:1.15.2
        args:
        - nginx
        - -g
        - daemon off;
        - -c
        - /nginx/nginx.conf
        volumeMounts:
        - mountPath: /nginx/
          name: prometheus-nginx
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
      volumes:
      - name: prometheus-nginx
        configMap:
          defaultMode: 438
          items:
          - key: nginx.conf
            mode: 438
            path: nginx.conf
          name: {{ template "prometheus.fullname" . }}
