{{- if .Values.enableDaemonSet }}
{{- if .Values.global.rbacEnable }}
{{- if .Values.global.pspEnable }}
{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1beta1" }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- else if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1alpha1" }}
apiVersion: rbac.authorization.k8s.io/v1alpha1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
{{- end }}
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ template "exporter-node.name" . }}
    chart: {{ template "exporter-node.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "exporter-node.psp.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "exporter-node.psp.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "exporter-node.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}
