{{- if .Values.enabled }}
apiVersion: {{ template "prometheus-operator.apiVersion" . }}
kind: Alertmanager
metadata:
  labels:
    app: {{ template "alertmanager.name" . }}
    chart: {{ template "alertmanager.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
  name: {{ .Release.Name }}
spec:
  baseImage: "{{ .Values.image.repository }}"
{{- if .Values.externalUrl }}
  externalUrl: "{{ .Values.externalUrl }}"
{{- else if .Values.ingress.enabled }}
  externalUrl: "http://{{ index .Values.ingress.hosts 0 }}{{ .Values.routePrefix }}"
{{- else }}
  externalUrl: http://{{ template "alertmanager.dnsname" . }}.{{ .Release.Namespace }}:9093
{{- end }}
{{- if .Values.nodeSelector }}
  nodeSelector:
{{ toYaml .Values.nodeSelector | indent 4 }}
{{- end }}
  paused: {{ .Values.paused }}
  replicas: {{ .Values.replicaCount }}
  resources:
{{ toYaml .Values.resources | indent 4 }}
{{- if or .Values.storageSpec .Values.persistence.enabled }}
  storage:
    volumeClaimTemplate:
      spec:
{{- if .Values.storageSpec }}
{{ toYaml .Values.storageSpec | indent 8 }}
{{- else }}
        storageClassName: {{ default "default" .Values.persistence.storageClass }}
        accessModes: 
          - {{ default "ReadWriteOnce" .Values.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
{{- end }}
{{- end }}
  version: "{{ .Values.image.tag }}"
{{- if eq .Values.podAntiAffinity "hard" }}
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: kubernetes.io/hostname
        labelSelector:
          matchLabels:
            app: {{ template "alertmanager.name" . }}
            alertmanager: {{ .Release.Name }}
{{- else if eq .Values.podAntiAffinity "soft" }}
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app: {{ template "alertmanager.name" . }}
              alertmanager: {{ .Release.Name }}
{{- end }}
{{- if .Values.tolerations }}
  tolerations:
{{ toYaml .Values.tolerations | indent 4 }}
{{- end }}
  imagePullSecrets:
{{ toYaml .Values.global.imagePullSecrets | indent 4 }}
{{- end }}